### ISSUE TITLE
Site's title

### ISSUE THREAD

**Issue by dizak** [cheminfIBB/cheminfibb.github.io#10]
# Proposed change

We spoke about changing the site's title to something else than a copy of our organisation. What should be the name then?

**Comment by henryk69** [comment]
which file contains the site's title?
I propose:

**Department of Bioinformatics**
bio- and cheminformatics facility  
at the
Institute of Biochemistry and Biophysics PAS
Warsaw, Poland

**Comment by dizak** [comment]
It is defined as a variable in the ```_config.yml``` file. There are two variables for what you have proposed:

- title
- description

For now, we just use the title.

**Comment by dizak** [comment]
Resolved by #12
