### ISSUE TITLE
People formatting

### ISSUE THREAD

**Issue by dizak** [cheminfIBB/cheminfibb.github.io#11]
# Proposed change

We spoke about a collapsable list of hired people. How should it look actually?

**Comment by henryk69** [comment]
I would propose:

* Head of Department: 
prof. Piotr Zielenkiewicz, PhD 

* Principal investigators:
SK
Dorota Niedziałek, PhD
Piotr Pawłowski, PhD
Pawel Siedlecki, PhD (pic, email, more)

* Staff
Agnieszka Gromadka
Piotr Zarębski
Albert Bogdanowicz  

* PhD Students:
Dariusz Izak (pic, email, more)
Marta Stępniewska-Dziubińska
Małgorzata Habich
Rafał Jastrząb

* Students:
Jakub Poziemski

* Alumni:
Maciej Wójcikowski PhD, currently at Merck
Anna Łukasik PhD, AstraZeneca
Arkadiusz Gładki PhD, Roche
prof. Andrzej Kierzek, Certara
Jerzy Dyczkowski PhD, Roche
Danuta Płochocka PhD, (emeritus)

clicking on the name links to personal site which can be further modified by each dept. member

**Comment by Setnea** [comment]
Am I getting excluded? ;)

**Comment by Setnea** [comment]
I think people within each category (PhD/Alumni etc) should be listed in alphabetical/chronological* order.

*time they joined/left

**Comment by henryk69** [comment]
> Am I getting excluded? ;)

its the only reasonable explanation! :-)
what section should I put you in?

**Comment by Setnea** [comment]
Um, that's tricky I am neither PI nor PhD, I'm just a simple bioinformatician looking for more RAM.
I'm fine with being categorized as "staff", this term could be also used for our admins if they're fine with that.

**Comment by henryk69** [comment]
> Um, that's tricky I am neither PI nor PhD, I'm just a simple bioinformatician looking for more RAM.
> I'm fine with being categorized as "staff", this term could be also used for our admins if they're fine with that.

Does it look good now?

**Comment by dizak** [comment]
I have just pushed a dirty-but-working version showing how it can look like. The html itself fine but there are  two potential problems:

1. The style is defined as div and img properties. This is not very elegant but technically just fine. I believe it can be accepted for now if it has to and moved to ```assets/css/main.scss``` later.

2. This does not collapse when the browser's window is squeezed. It should be tested on mobile.

There are two cases shown, with and without the long description.

**Comment by dizak** [comment]
I have added another solution, using the ```flexbox```. I believe, this is the way as it scales fine, unlike ```float```. I have also annotated each for your convenience.

@henryk69 @Setnea Please view the recent changes and let me know which version should stay. I strongly suggest the ```flexbox```.

**Comment by dizak** [comment]
@henryk69 @Setnea I have just pushed another commit.

1. The CSS was moved to ```main.scss``` and made into classes, ids and so on.
2. Made the long description show up on the mouse-hover. It should work on the mobile with clicks too.

**Comment by Setnea** [comment]
Flexbox looks good. I think long descriptions should be moved to "subpages", available by clicking on given member name/photo.
Moreover, I would add short info about the main field of interests/studies below name-email-etc.

**Comment by henryk69** [comment]
ok I'm working on this issue today.

**Comment by henryk69** [comment]
resolved
