### ISSUE TITLE
main page text

### ISSUE THREAD

**Issue by henryk69** [cheminfIBB/cheminfibb.github.io#15]
# Proposed feature

In the index.html file add text which will be shown as title page. 

<h1><u>Department of Bioinformatics</u></h1>
<h2>Bio- and cheminformatics facility</h2>

<h4>Institute of Biochemistry and Biophysics, Polish Academy of Sciences, Warsaw</h4>

(...)

**Comment by dizak** [comment]
Resolved with #16
