### ISSUE TITLE
Add section "Publications" to main menu

### ISSUE THREAD

**Issue by henryk69** [cheminfIBB/cheminfibb.github.io#22]
# Proposed feature

adding Publications section will be beneficial for obvious reasons (TM)

**Comment by henryk69** [comment]
proposed subsections :
### Selected publications (highlights)
### Five years publications (used for grant proposals)
### Older publications (history)

**Comment by dizak** [comment]
OK, what about the content for each of these subsections? Should I just leave it for now?

**Comment by henryk69** [comment]
> OK, what about the content for each of these subsections? Should I just leave it for now?

content should be generated automatically. Of course beside "Selected publications" which we will do separately. For now it can be empty. I will make a milestone for the automatic generation pubs.

**Comment by henryk69** [comment]
Done for the most part. I would like to close this issue and create a new one, listing all minor updates needed. There is a milestone here...

**Comment by henryk69** [comment]
resolved
