### ISSUE TITLE
Change order of main menu (left bar)

### ISSUE THREAD

**Issue by henryk69** [cheminfIBB/cheminfibb.github.io#24]
# Proposed change

change the order of pages so it becomes more consistant:

About us
People
Publications
Services
Software
Resources

**Comment by Setnea** [comment]
What about the idea to move the content of "about us" section to the main page?

**Comment by henryk69** [comment]
IDK, front page should be something like a quick highlights: 
 - main interests:  Targets and drug/tools discovery, Population genetics, data analysis, systems biology/ precission medicine
- maybe 'news' can also be here? 
- pictures/graphics


This page should be relatively short and - if interested - additional info is available on the left.
