### ISSUE TITLE
Add new fields to left menubar

### ISSUE THREAD

**Issue by henryk69** [cheminfIBB/cheminfibb.github.io#25]
# Proposed feature

add structural project to menubar. At the end of the list create four new entries:

--- (some kind of visual separator?)

PL.OpenScreen
This is the Polish webpage for [EU.OpenScreen](https://www.eu-openscreen.eu)

PL.ELIXIR
This is the Polish webpage for [EU.ELIXIR](https://www.elixir-europe.org/)

PL.GBIF
This is the Polish webpage for [GBIF](https://www.gbif.org)

PL.EURO-BIOIMAGING
This is the Polish webpage for [EURO-BIOIMAGING](http://www.eurobioimaging.eu/)

**Comment by henryk69** [comment]
onit!

**Comment by dizak** [comment]
How it should look like? Should the link go to these websites directly from the sidebar link? Or what you have pasted should be as the sub-page content?

**Comment by henryk69** [comment]
I imagined this as a (almost) empty page with oonly this short sentence linking to the projects european headquaters

**Comment by dizak** [comment]
Done. What should be the order in the sidebar?

**Comment by henryk69** [comment]
Order:
<sep>
PL.OpenScreen
PL.ELIXIR
PL.GBIF
PL.EURO-BIOIMAGING
