### ISSUE TITLE
English content

### ISSUE THREAD

**Issue by dizak** [cheminfIBB/cheminfibb.github.io#9]
# Proposed change

All the sub-pages should be in English. Files to convert:
- [x] ```index.html```
- [x] ```services.md```
- [x] ```people.md```

**Comment by henryk69** [comment]
Services will be divided into 3 categories: 
- Cheminformatics & structural biology <- eng. OK
- Genomics <- partialy done
- Data mining <- not done

Missing english text will be addressed in separate issues.

**Comment by henryk69** [comment]
Will be updating index.html shortly

**Comment by henryk69** [comment]
ENH #37 fixes about-us.md <- ticked as "done"

**Comment by henryk69** [comment]
everything done. Closing.
